#!/bin/bash
#Subject
SUBJECT="System Update $(date | awk '{print $4}')"
# To
TOEMAIL="pialerts37@gmail.com"
# Message
cd /home/pi/Documents/Coding/Scripts
EMAILMESSAGE="message.txt"

uptime  > $EMAILMESSAGE
echo "Current $(vcgencmd measure_temp)" >> $EMAILMESSAGE
echo "" >> $EMAILMESSAGE

tail -20 /var/log/auth.log >> $EMAILMESSAGE
# Sending email using /bin/mail
mail -s "$SUBJECT" "$TOEMAIL" < $EMAILMESSAGE
