#!/bin/bash
#Subject
SUBJECT="System Update $(date)"
# To
TOEMAIL="pialerts37@gmail.com"
# Message
EMAILMESSAGE="message.txt"
uptime  > $EMAILMESSAGE
vcgencmd measure_temp >> $EMAILMESSAGE
# Sending email using /bin/mail
mail -s "$SUBJECT" "$TOEMAIL" < $EMAILMESSAGE
