#!/bin/bash
#Subject
SUBJECT="System Update $(date | awk '{print $4}')"
# To
TOEMAIL="pialerts37@gmail.com"
# Message
cd /home/pi/Documents/Coding/Scripts
EMAILMESSAGE="message.txt"

echo "Uptime: $(uptime)"  > $EMAILMESSAGE
echo "Current $(vcgencmd measure_temp)" >> $EMAILMESSAGE
echo "" >> $EMAILMESSAGE

# See SSH Attempts
TEMPFILE="tempLog.txt"
grep "$(date +"%b %d")" /var/log/auth.log > $TEMPFILE
echo "There were $(grep -i -c "disconnect" tempLog.txt) failed SSH attempts so far today." >> $EMAILMESSAGE
echo ""  >> $EMAILMESSAGE
cat tempLog.txt >> $EMAILMESSAGE
# Sending email using /bin/mail
mail -s "$SUBJECT" "$TOEMAIL" < $EMAILMESSAGE
