#!/bin/bash
#Subject
SUBJECT="Temperature $(date)"
# To
TOEMAIL="pialerts37@gmail.com"
# Message
cd /home/pi/Documents/Scripts
EMAILMESSAGE="temp.txt"

vcgencmd measure_temp >> $EMAILMESSAGE
# Sending email using /bin/mail
mail -s "$SUBJECT" "$TOEMAIL" < $EMAILMESSAGE
